data: ../datasets/barangay178_rain/data.yaml

epochs: 60

batch: 12

imgsz: 640

optimizer: AdamW

learning_rate: 0.001

workers: 4

patience: 20

device: 0

cache: ram

project: ../experiments

experiment_name: experiment_rain_001

dataset_version: barangay178_rain